Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopManagement.Models;

namespace ShopManagement.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly shop_managerContext _context;

        public PaymentsController(shop_managerContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Payments.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payments == null)
            {
                return NotFound();
            }

            return View(payments);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Workingdays,TicketValue,TicketNo,Salary,Bonus")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payments);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(payments);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments.FindAsync(id);
            if (payments == null)
            {
                return NotFound();
            }
            return View(payments);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Workingdays,TicketValue,TicketNo,Salary,Bonus")] Payments payments)
        {
            if (id != payments.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentsExists(payments.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(payments);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payments == null)
            {
                return NotFound();
            }

            return View(payments);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payments = await _context.Payments.FindAsync(id);
            _context.Payments.Remove(payments);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentsExists(int id)
        {
            return _context.Payments.Any(e => e.Id == id);
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopManagement.Models;

namespace ShopManagement.Controllers
{
    public class ProductsController : Controller
    {
        private readonly shop_managerContext _context;

        public ProductsController(shop_managerContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchProduct)
        {
            var shop_managerContext = from s in _context.Product select s;

            if (!String.IsNullOrEmpty(searchProduct))
            {
                shop_managerContext = shop_managerContext.Where(s => s.Name.Contains(searchProduct));

            }
            return View(await shop_managerContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Weight,Category,Quantity,Availableqty")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.Quantity = 0;
                product.Availableqty = 0;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Weight,Category,Quantity,Availableqty")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopManagement.Models;
using ShopManagement.ViewModels;

namespace ShopManagement.Controllers
{
    public class StaffsController : Controller
    {
        private readonly shop_managerContext _context;

        public StaffsController(shop_managerContext context)
        {
            
            _context = context;
        }

        public IActionResult Login()
        {
           // TempData.Keep("staffoccupationID");
            TempData["staffoccupationID"] = 0;
            TempData["staffusername"] = "";
            TempData["staffid"] = 0;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("Username,Password")] Staff login)
        {
            var loginInfo = _context.Staff.Where(s => s.Username == login.Username && s.Password == login.Password).FirstOrDefault();

            if (loginInfo == null)
            {
                return (RedirectToAction(nameof(Login)));
            }
            else
            {
                TempData["staffoccupationID"] = loginInfo.StaffoccupationId;
                TempData["tsusername"] = loginInfo.Username;
                TempData["staffid"] = loginInfo.Id;
                return RedirectToAction("Details", new { id = loginInfo.Id });
            }
        }

        public IActionResult Logout()
        {
            return RedirectToAction(nameof(Login));
        }

        // GET: Staffs
        public async Task<IActionResult> Index(string searchStaff)
        {
            var shop_managerContext = from s in _context.Staff select s;

            if (!String.IsNullOrEmpty(searchStaff))
            {
                shop_managerContext = shop_managerContext.Include(s => s.Payments).Include(s => s.Staffoccupation).Where(s => s.Username.Contains(searchStaff));
                
            }
            return View(await shop_managerContext.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Payments)
                .Include(s => s.Staffoccupation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            ViewData["PaymentsId"] = new SelectList(_context.Payments, "Id", "Id");
            ViewData["StaffoccupationId"] = new SelectList(_context.Staffoccupation, "Id", "Id");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Firstname,Lastname,Email,Phone,Address,StaffoccupationId,PaymentsId")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentsId"] = new SelectList(_context.Payments, "Id", "Id", staff.PaymentsId);
            ViewData["StaffoccupationId"] = new SelectList(_context.Staffoccupation, "Id", "Id", staff.StaffoccupationId);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            ViewData["PaymentsId"] = new SelectList(_context.Payments, "Id", "Id", staff.PaymentsId);
            ViewData["StaffoccupationId"] = new SelectList(_context.Staffoccupation, "Id", "Id", staff.StaffoccupationId);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Firstname,Lastname,Email,Phone,Address,StaffoccupationId,PaymentsId")] Staff staff)
        {

            if (id != staff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentsId"] = new SelectList(_context.Payments, "Id", "Id", staff.PaymentsId);
            ViewData["StaffoccupationId"] = new SelectList(_context.Staffoccupation, "Id", "Id", staff.StaffoccupationId);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Payments)
                .Include(s => s.Staffoccupation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_MaintenanceLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopManagement - Maintenance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Maintenance</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Downtimes" asp-action="Index">Downtimes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Equipments" asp-action="Index">Equipments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Orderproducts" asp-action="Index">Orderproducts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["staffid"]">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopManagement - Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Manager</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Downtimes" asp-action="Index">Downtimes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Equipments" asp-action="Index">Equipments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Orderproducts" asp-action="Index">Orderproducts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Payments" asp-action="Index">Payments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffoccupations" asp-action="Index">Staffoccupations</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Index">Staffs</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["staffid"]">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_SalesLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopManagement - Sales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sales</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Downtimes" asp-action="Index">Downtimes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Equipments" asp-action="Index">Equipments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Orderproducts" asp-action="Index">Orderproducts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["staffid"]">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_WorkerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopManagement - Worker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Worker</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Downtimes" asp-action="Index">Downtimes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Equipments" asp-action="Index">Equipments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Orderproducts" asp-action="Index">Orderproducts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["staffid"]">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>